# Generated by Django 4.1.7 on 2023-09-13 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churchwebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True, max_length=255)),
                ('web_link', models.URLField(blank=True, verbose_name='Website Address')),
                ('image', models.ImageField(null=True, upload_to='img/')),
                ('path', models.TextField(blank=True, max_length=120)),
            ],
        )
    ]
