# Generated by Django 4.1.7 on 2023-12-28 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churchwebsite', '0002_churchuser_course_imagedata2_location_event'),
    ]

    operations = [
        
        migrations.RenameModel(
            old_name='toberemoved',
            new_name='ImagePath',
        ),
        
    ]
