# Generated by Django 4.1.7 on 2023-12-28 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churchwebsite', '0002_churchuser_course_imagedata2_location_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='churchUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120, verbose_name='Course Name')),
                ('web_link', models.URLField(blank=True, verbose_name='Website Address')),
                ('grade', models.CharField(max_length=40, verbose_name='Grade')),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='course/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Location Name')),
                ('address', models.CharField(max_length=240)),
                ('zip_code', models.CharField(max_length=5, verbose_name='Zip Code')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Contact Phone')),
                ('location_image', models.ImageField(blank=True, null=True, upload_to='website/img/events')),
                ('organizer', models.IntegerField(default=1, verbose_name='Organizer')),
            ],
        ),
        migrations.RenameModel(
            old_name='ImageData2',
            new_name='ImageData',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('location', models.CharField(max_length=200, verbose_name='Event Location')),
                ('attendees', models.CharField(max_length=120, verbose_name='Participants')),
                ('description', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
