# Generated by Django 4.1.7 on 2023-04-14 06:27

import churchwebsite.filechecker
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchwebsite', '0003_course_imagedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='image',
            field=models.ImageField(null=True, upload_to='img/', validators=[churchwebsite.filechecker.file_size]),
        ),
    ]
